# Generated by Django 3.2.2 on 2021-05-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='passport',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
    ]
