# Generated by Django 3.2.2 on 2021-05-16 10:12

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210508_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='passport',
            field=models.FileField(upload_to='private/documents', validators=[resources.models.is_zip_validator]),
        ),
    ]
