# Generated by Django 3.2.2 on 2021-05-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0005_alter_pet_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='passport',
        ),
        migrations.AddField(
            model_name='pet',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
