# Generated by Django 3.2.2 on 2021-05-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20210516_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='created_by',
        ),
    ]
